### ISSUE TITLE
Image on fullscreen never changes (Android)

### ISSUE THREAD

**Issue by wilguevara** [keensoft/FullScreenImage-Cordova-Plugin#13]
Hi @slaptot i have a issue on android 4.2.2, when i try to open a new image in the fullscreen viewer, it is always showing the first image i have ever opened for the first time of the life of my app. 
Does you need more details about the problems for helping me?

King regards!
PD: on iOS everything works really fine!

**Comment by wilguevara** [comment]
Hello @slaptot any news?

**Comment by wilguevara** [comment]
@slaptot i have been watching the code and i think i know why is this issue happening, is because the downloaded isn't deleted before opening another file or after going out the preview image . i will try doing a work around of this issue and send you any updates if i can fix it.

**Comment by wilguevara** [comment]
Hello @slaptot here is a fix i do:
Since the problem is just on android so you have to update de FullScreenImage.java file

**add these code just after line 108:**
<code>
if(f.exists() && !f.isDirectory()) {
                boolean bReturn = f.delete();
            }
</code>

and add these other just after line 158:
<code>if(filePath.exists() && !filePath.isDirectory()) {
                boolean bReturn  = filePath.delete();
            }</code>

this is actually working for me, i have tested only on android 4.2.2

**Comment by slaptot** [comment]
Hi @wilguevara ,
please make a pull request for it. Every enhancement we could do it´s good for all. Any way, we provide a string name in order to avoid this problem, so the app handle this problem (duplicate files in filesystem). Good job and Thanks!

**Comment by L-VE** [comment]
I had the same problem opening a base64 image string. The file that was opening in fullscreen, was written in storage under the name of output.jpg. Then I took a look at the java code and noticed that all the data of the file I was trying to open was just appended to the already existing "output.jpg" file. That's because of this line of code:

FileOutputStream os = new FileOutputStream(filePath, true); (on line 155)

You can change true to false to overwrite the "output.jpg" file. 
This worked for me.

**Comment by wilguevara** [comment]
@L-VE +1 thanks! i'll try this.

**Comment by slaptot** [comment]
@L-VE +1 thanks! Merged
