### ISSUE TITLE
Nothing happens...

### ISSUE THREAD

**Issue by jaredgreener** [keensoft/FullScreenImage-Cordova-Plugin#4]
For some reason when I load a base64 string, nothing pops up. Any ideas? My base64 string is  consoling out just fine, but nothing happens on the device.

Thanks!

function convertImgToBase64URL(url, callback, outputFormat){
    var canvas = document.createElement('CANVAS'),
        ctx = canvas.getContext('2d'),
        img = new Image;
    img.crossOrigin = 'Anonymous';
    img.onload = function(){
        var dataURL;
        canvas.height = img.height;
        canvas.width = img.width;
        ctx.drawImage(img, 0, 0);
        dataURL = canvas.toDataURL(outputFormat);
        console.log("loaded base64");
        callback.call(this, dataURL);
        canvas = null; 
    };
    img.src = url;
}

function loadImageViewer(link, title){
	
	console.log("0");
	
	convertImgToBase64URL(link, function(base64String) {

		console.log("1");
		FullScreenImage.showImageURL(base64String, title);
		console.log(base64String);
	});
	
}

**Comment by slaptot** [comment]
You should use "showImageBase64" instead of "showImageURL":
ie. FullScreenImage.showImageBase64(base64,name,type);

and try to load base64 image without Html headers:
imageBase64JPEG = "/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAMCAgM...........SXEs6fwv//Z";

Any way, try to get latest version and check example project attachment. Let me know your tests ;)

**Comment by jaredgreener** [comment]
That did it - thanks! I should have looked at the example app, but the example in the readme shows the same function twice for both methods. For future users it may be helpful to update that.


Thanks!
